-- Use role 
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DB_SF_TEST;

CREATE SCHEMA IF NOT EXISTS DB_SF_TEST.STAGING;
CREATE SCHEMA IF NOT EXISTS DB_SF_TEST.INTEGRATION;
CREATE SCHEMA IF NOT EXISTS DB_SF_TEST.PRESENTATION;
CREATE SCHEMA IF NOT EXISTS DB_SF_TEST.DATA_REPO COMMENT ='FINAL LAYER';

